services:
  db:
    image: postgres
    container_name: crop_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./query.sql:/docker-entrypoint-initdb.d/init.sql

  web_app:
    container_name: web_app
    build:
      context: ./web_app
    ports:
      - "8000:8000"
    volumes:
      - ./photos:/app/photos

  message_broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Port, przez który kod wysyła wiadomości
      - "15672:15672" # tu odpalasz przeglądarkę (Panel Admina)
    restart: always

  data_service:
    container_name: data_service
    build:
      context: ./data_service


  data_acquisition:
    container_name: data_acquisition
    build:
      context: ./data_acquisition

  ai_system:
    container_name: ai_system
    build:
      context: ./ai_system
    ports:
      - "8501:8501"
    depends_on:
      - data_acquisition
