services:
  db:
    image: postgres
    container_name: crop_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web_app:
    container_name: crop_web
    build:
      context: ./web_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  data_service:
    container_name: crop_data
    build:
      context: ./data_service
    ports:
      - "5000:5000"


  data_acquisition:
    container_name: crop_data_acquisition
    build:
      context: ./data_acquisition


  ai_system:
    container_name: crop_ai_system
    build:
      context: ./ai_system
    ports:
      - "8501:8501"
    depends_on:
      - data_acquisition