services:
  db:
    image: postgres
    container_name: crop_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./query.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web_app:
    container_name: web_app
    build:
      context: ./web_app
    ports:
      - "8000:8000"
    volumes:
      - ./photos:/app/photos

  data_broker:
    image: rabbitmq:3-management
    container_name: data_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  data_service:
    container_name: data_service
    build:
      context: ./data_service


  data_acquisition:
    container_name: data_acquisition
    build:
      context: ./data_acquisition
    ports:
      - "5000:5000"
    depends_on:
      - data_broker
    environment:
        RABBITMQ_HOST: data_broker
        RABBITMQ_PORT: 5672


  ai_system:
    container_name: ai_system
    build:
      context: ./ai_system
    ports:
      - "8501:8501"
    depends_on:
      - data_broker
      - db
    environment:
      RABBITMQ_HOST: data_broker